[tool.poetry]
name = "paper-embedding-demo"
version = "0.1.0"
description = ""
authors = ["h-tomo-tohoku <hara.tomomasa.s8@dc.tohoku.ac.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
